[workspace]
members = [
    "proto/gen/rust",
    "rust/cli",
    "rust/core",
    "rust/dbt-converter",
    "rust/pbjson-types",
    "rust/sqlinference",
    "rust/wasm-binding"
]
resolver = "2"

[workspace.dependencies]
cargo-nextest = "0.9"